---
- name: check the given numbet is less then or grater then
  hosts: localhost
  vars_prompt:
    name: number
    prompt: Enter the number to validate
    private: no
  tasks:
    - name: Validate the number
      ansible.builtin.debug:
        msg: "Given number is {{number}} less than 10"
      when: number | int < 10
  tasks:
    - name: Validate given number
      ansible.builtin.debug:
        msg: "Given number is {{number}} grater then 10"
      when: number | int >= 10
