---
- name: Verifying filters
  hosts: localhost
  tasks:
    - name: filter for default variable
      ansible.builtin.debug:
        msg: "Hello {{Cource | default ('Ansible')}}"
  tasks:
    - name: uppar case
      vars: 
      Message: "Hello Good Morning Pavan"
      ansible.builtin.debug:
        msg: "{{ Message | upper }}"