---
- name: Verifying filters
  hosts: localhost
  tasks:
    - name: filter for default variable
      ansible.builtin.debug:
        msg: "Hello {{Cource | default ('Ansible')}}"

- name: Verifying upper case and lower case
  hosts: localhost
  vars:
    message: Hello I must say good morning
  tasks:
    - name: upper case
      ansible.builtin.debug:
        msg: "{{ message | upper }}"
        msg: "{{ message | lower }}"

- name: Remove duplicate in the list 
  hosts: localhost
  vars:
    numbers: [1, 2, 3, 4, 4, 5, 5, 6]
  tasks:
    - name: uniqu numbers
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

- name: Dictionary to list
  hosts: localhost
  vars: # this is called dictonary
    my_dict:
      Cource: DevOps
      Trainer: Pavan
      Duration: 120hr
  tasks: 
  - name: Dic to list
    ansible.builtin.debug:
      msg: "Before converstion {{ my_dict }}"
  - name: After converstion
    ansible.builtin.debug:
      msg: " After converstion {{ my_dict | dict2items }}"
