---
- name: Verifying filters
  hosts: localhost
  tasks:
    - name: filter for default variable
      ansible.builtin.debug:
        msg: "Hello {{Cource | default ('Ansible')}}"

- name: Verifying upper case and lower case
  hosts: localhost
  vars:
    message: Hello I must say good morning
  tasks:
    - name: upper case
      ansible.builtin.debug:
        msg: "{{ message | upper }}"
        msg: "{{ message | lower }}"

- name: Remove duplicate in the list 
  hosts: localhost
  number: [1, 2, 3, 4, 4, 5, 5, 6]
  tasks:
    - name: uniqu numbers
      ansible.builtin.debug:
        msg: "{{ number | unique }}"