---
- name: loops demo 
  hosts: localhost
  tasks:
    - name: print loop items
      ansible.builtin.debug:
        msg: "Hello welcome to {{ item }}"
      loop:
        - linux
        - shell
        - MySql

- name: install pakages
  hosts: localhost
  ansible.builtin.dnf:
    name: {{ item }}
    state: latest
  loop:
  - nginx
  - mysql
  - postfix