---
- name: install pakages
  hosts: localhost
  become: yes
  tasks:
  - name: packge install
    ansible.builtin.dnf:
      name: "{{ item.name }}"
      state: "{{ state.latest }}"
    loop:
    - { name: 'nginx' , state: 'latest' }
    - { name: 'mysql' , state: 'absent' }
    - { name: 'postfix' , state: 'absent' }