---
- name: examples on register variable
  hosts: localhost
  tasks: 
  - name: show the disk space
    ansible.builtin.shell: df -hT
    register: disk_space
  - name: print the disc disk_spac
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "disk_space.stdout_lines"