---
- name: Shell module examples
  hosts: localhost
  tasks:
  - name: date display
    ansible.builtin.shell: date
    rigster: date
  - name: display the date
    ansible.builtin.debug:
      msg: "{{date}}"