---
- name: check user is super user or not
  hosts: localhost
  tasks: 
    - name: chek user status
      ansible.builtin.command: whoami
      register: USER
    - name: print user information
      debug:
        msg: "User is {{USER.stdout}}"
    - name: Check user is root or not
      debug:
        when: USER.stdout != "root"
        msg: "User is not a root user"