---
- name: check user is super user or not
  hosts: localhost
  tasks: 
    - name: chek user status
      ansible.builtin.command: whoami
      register: USER
    - name: print user information
      debug:
        msg: "User is {{USER.stdout}}"
    - name: Check user is root or not
      debug:
        msg: "User is not a root user"
      when: USER.stdout != 'root'
    - name: Make user a superuser
      become: yes
      become_user: root
      command: "{{ USER.stdout }} ALL=(ALL) NOPASSWD:ALL"
      when: USER.stdout != 'root'
