---
- name: install niginx
  hosts: localhost
  tasks: 
    - name: ensure nginx is at the latest version
      ansible.builtin.apt : name=nginx state=latest
    - name: "start nginx"
      service: 
        name: nginx
        state: started