---
- name: install niginx
  hosts: localhost
  become: yes
  tasks: 
    - name: ensure nginx is at the latest version
      yum:
        name: nginx
        state: latest
    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes  # if you want to also enable nginx
      register: State
    - name: print if the nginx installed
      debug:
        msg: "Hello status is {{State}}"