---
- name: Variable from Task level
  hosts: localhost
  vars: 
    Cource: ansible
    Trainer: Pavan
    duration: 120 hours
  tasks:
    - name: calling variable from Task
      vars:
        Cource: DevOps
        Trainer: shiva
      ansible.builtin.debug:
        msg: "Today is {{Cource}} and Mighty {{Trainer}}"
    - name: Global varibles
      ansible.builtin.debug:
        msg: "Today is {{Cource}} and Mighty {{Trainer}}"
