- name: user name and password
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your user name
    private: false
  - password : Password
    prompt: Please enter your user name
    private: true
  tasks: 
  - name: print user information
    ansible.builtin.debug:
      msg: "Hello {{USERNAME}} & your password is {{Password}}"